apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-a-webhook-git-dev-repo
spec:
  steps:
    - name: echo
      image: fedora
      script: |
        #!/usr/bin/env bash
        curl -u 'simonDelordtest:f6c80580cdb018d5d004f45265ab7277e66caecf' -H "Content-Type: application/json" -X POST -d '{"config":{"url":"http://git-dev-app1-listener-default.apps.ocpbare.melbourneocp.net", "content_type":"json"}}' https://api.github.com/repos/simonDelordtest/dev-repo-app1/hooks

