apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-a-dev-git-repo
spec:
  steps:
    - name: echo
      image: fedora
      script: |
        #!/usr/bin/env bash
        curl -u 'simonDelordtest:136f9f506e4a260de05b933d23c5aecf7834834c' https://api.github.com/user/repos -d '{"name":"dev-repo-app1"}'

