apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  steps:
    - name: echo
      image: fedora
      script: |
        #!/usr/bin/env bash
        sleep 10
        echo "Test successful"
